name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read
  pages: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      - name: Preprocess contents
        run: python3 shtml.py
      - name: Configure Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build/
  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
